// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceType int32

const (
	DeviceType_DeviceInvalid    DeviceType = 0
	DeviceType_DeviceTestSignal DeviceType = 1
	DeviceType_DeviceAirspyOne  DeviceType = 2
	DeviceType_DeviceAirspyHf   DeviceType = 3
	DeviceType_DeviceRtlsdr     DeviceType = 4
	DeviceType_DeviceLimeSDR    DeviceType = 5
	DeviceType_DeviceSpyServer  DeviceType = 6
	DeviceType_DeviceHackRF     DeviceType = 7
)

var DeviceType_name = map[int32]string{
	0: "DeviceInvalid",
	1: "DeviceTestSignal",
	2: "DeviceAirspyOne",
	3: "DeviceAirspyHf",
	4: "DeviceRtlsdr",
	5: "DeviceLimeSDR",
	6: "DeviceSpyServer",
	7: "DeviceHackRF",
}

var DeviceType_value = map[string]int32{
	"DeviceInvalid":    0,
	"DeviceTestSignal": 1,
	"DeviceAirspyOne":  2,
	"DeviceAirspyHf":   3,
	"DeviceRtlsdr":     4,
	"DeviceLimeSDR":    5,
	"DeviceSpyServer":  6,
	"DeviceHackRF":     7,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}

func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

type StatusType int32

const (
	StatusType_Invalid StatusType = 0
	StatusType_OK      StatusType = 1
	StatusType_Error   StatusType = 2
)

var StatusType_name = map[int32]string{
	0: "Invalid",
	1: "OK",
	2: "Error",
}

var StatusType_value = map[string]int32{
	"Invalid": 0,
	"OK":      1,
	"Error":   2,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

type Session struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeviceInfo struct {
	DeviceType           DeviceType    `protobuf:"varint,1,opt,name=DeviceType,proto3,enum=protocol.DeviceType" json:"DeviceType,omitempty"`
	StreamConfig         *StreamConfig `protobuf:"bytes,2,opt,name=StreamConfig,proto3" json:"StreamConfig,omitempty"`
	Session              string        `protobuf:"bytes,3,opt,name=Session,proto3" json:"Session,omitempty"`
	DeviceSerial         string        `protobuf:"bytes,4,opt,name=DeviceSerial,proto3" json:"DeviceSerial,omitempty"`
	DeviceName           string        `protobuf:"bytes,5,opt,name=DeviceName,proto3" json:"DeviceName,omitempty"`
	MaximumSampleRate    uint32        `protobuf:"varint,6,opt,name=MaximumSampleRate,proto3" json:"MaximumSampleRate,omitempty"`
	MaximumGain          uint32        `protobuf:"varint,7,opt,name=MaximumGain,proto3" json:"MaximumGain,omitempty"`
	MaximumDecimation    uint32        `protobuf:"varint,8,opt,name=MaximumDecimation,proto3" json:"MaximumDecimation,omitempty"`
	MinimumFrequency     uint32        `protobuf:"varint,9,opt,name=MinimumFrequency,proto3" json:"MinimumFrequency,omitempty"`
	MaximumFrequency     uint32        `protobuf:"varint,10,opt,name=MaximumFrequency,proto3" json:"MaximumFrequency,omitempty"`
	ADCResolution        uint32        `protobuf:"varint,11,opt,name=ADCResolution,proto3" json:"ADCResolution,omitempty"`
	MaximumRXChannels    uint32        `protobuf:"varint,12,opt,name=MaximumRXChannels,proto3" json:"MaximumRXChannels,omitempty"`
	MaximumTXChannels    uint32        `protobuf:"varint,13,opt,name=MaximumTXChannels,proto3" json:"MaximumTXChannels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetDeviceType() DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return DeviceType_DeviceInvalid
}

func (m *DeviceInfo) GetStreamConfig() *StreamConfig {
	if m != nil {
		return m.StreamConfig
	}
	return nil
}

func (m *DeviceInfo) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *DeviceInfo) GetDeviceSerial() string {
	if m != nil {
		return m.DeviceSerial
	}
	return ""
}

func (m *DeviceInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *DeviceInfo) GetMaximumSampleRate() uint32 {
	if m != nil {
		return m.MaximumSampleRate
	}
	return 0
}

func (m *DeviceInfo) GetMaximumGain() uint32 {
	if m != nil {
		return m.MaximumGain
	}
	return 0
}

func (m *DeviceInfo) GetMaximumDecimation() uint32 {
	if m != nil {
		return m.MaximumDecimation
	}
	return 0
}

func (m *DeviceInfo) GetMinimumFrequency() uint32 {
	if m != nil {
		return m.MinimumFrequency
	}
	return 0
}

func (m *DeviceInfo) GetMaximumFrequency() uint32 {
	if m != nil {
		return m.MaximumFrequency
	}
	return 0
}

func (m *DeviceInfo) GetADCResolution() uint32 {
	if m != nil {
		return m.ADCResolution
	}
	return 0
}

func (m *DeviceInfo) GetMaximumRXChannels() uint32 {
	if m != nil {
		return m.MaximumRXChannels
	}
	return 0
}

func (m *DeviceInfo) GetMaximumTXChannels() uint32 {
	if m != nil {
		return m.MaximumTXChannels
	}
	return 0
}

type StreamConfig struct {
	RXC                  *ChannelConfig `protobuf:"bytes,1,opt,name=RXC,proto3" json:"RXC,omitempty"`
	TXC                  *ChannelConfig `protobuf:"bytes,2,opt,name=TXC,proto3" json:"TXC,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StreamConfig) Reset()         { *m = StreamConfig{} }
func (m *StreamConfig) String() string { return proto.CompactTextString(m) }
func (*StreamConfig) ProtoMessage()    {}
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *StreamConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamConfig.Unmarshal(m, b)
}
func (m *StreamConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamConfig.Marshal(b, m, deterministic)
}
func (m *StreamConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamConfig.Merge(m, src)
}
func (m *StreamConfig) XXX_Size() int {
	return xxx_messageInfo_StreamConfig.Size(m)
}
func (m *StreamConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StreamConfig proto.InternalMessageInfo

func (m *StreamConfig) GetRXC() *ChannelConfig {
	if m != nil {
		return m.RXC
	}
	return nil
}

func (m *StreamConfig) GetTXC() *ChannelConfig {
	if m != nil {
		return m.TXC
	}
	return nil
}

type ChannelConfig struct {
	CenterFrequency       uint32   `protobuf:"varint,1,opt,name=CenterFrequency,proto3" json:"CenterFrequency,omitempty"`
	SampleRate            uint32   `protobuf:"varint,2,opt,name=SampleRate,proto3" json:"SampleRate,omitempty"`
	Oversample            uint32   `protobuf:"varint,3,opt,name=Oversample,proto3" json:"Oversample,omitempty"`
	NormalizedGain        uint32   `protobuf:"varint,4,opt,name=NormalizedGain,proto3" json:"NormalizedGain,omitempty"`
	AnalogFilterBandwidth uint32   `protobuf:"varint,5,opt,name=AnalogFilterBandwidth,proto3" json:"AnalogFilterBandwidth,omitempty"`
	Antenna               string   `protobuf:"bytes,6,opt,name=Antenna,proto3" json:"Antenna,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ChannelConfig) Reset()         { *m = ChannelConfig{} }
func (m *ChannelConfig) String() string { return proto.CompactTextString(m) }
func (*ChannelConfig) ProtoMessage()    {}
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ChannelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelConfig.Unmarshal(m, b)
}
func (m *ChannelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelConfig.Marshal(b, m, deterministic)
}
func (m *ChannelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelConfig.Merge(m, src)
}
func (m *ChannelConfig) XXX_Size() int {
	return xxx_messageInfo_ChannelConfig.Size(m)
}
func (m *ChannelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelConfig proto.InternalMessageInfo

func (m *ChannelConfig) GetCenterFrequency() uint32 {
	if m != nil {
		return m.CenterFrequency
	}
	return 0
}

func (m *ChannelConfig) GetSampleRate() uint32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

func (m *ChannelConfig) GetOversample() uint32 {
	if m != nil {
		return m.Oversample
	}
	return 0
}

func (m *ChannelConfig) GetNormalizedGain() uint32 {
	if m != nil {
		return m.NormalizedGain
	}
	return 0
}

func (m *ChannelConfig) GetAnalogFilterBandwidth() uint32 {
	if m != nil {
		return m.AnalogFilterBandwidth
	}
	return 0
}

func (m *ChannelConfig) GetAntenna() string {
	if m != nil {
		return m.Antenna
	}
	return ""
}

type IQData struct {
	Timestamp            uint64     `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Status               StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.StatusType" json:"status,omitempty"`
	Samples              []float32  `protobuf:"fixed32,4,rep,packed,name=Samples,proto3" json:"Samples,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IQData) Reset()         { *m = IQData{} }
func (m *IQData) String() string { return proto.CompactTextString(m) }
func (*IQData) ProtoMessage()    {}
func (*IQData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *IQData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IQData.Unmarshal(m, b)
}
func (m *IQData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IQData.Marshal(b, m, deterministic)
}
func (m *IQData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IQData.Merge(m, src)
}
func (m *IQData) XXX_Size() int {
	return xxx_messageInfo_IQData.Size(m)
}
func (m *IQData) XXX_DiscardUnknown() {
	xxx_messageInfo_IQData.DiscardUnknown(m)
}

var xxx_messageInfo_IQData proto.InternalMessageInfo

func (m *IQData) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *IQData) GetStatus() StatusType {
	if m != nil {
		return m.Status
	}
	return StatusType_Invalid
}

func (m *IQData) GetSamples() []float32 {
	if m != nil {
		return m.Samples
	}
	return nil
}

func (m *IQData) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeviceList struct {
	Devices              []*DeviceInfo `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceList) Reset()         { *m = DeviceList{} }
func (m *DeviceList) String() string { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()    {}
func (*DeviceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *DeviceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceList.Unmarshal(m, b)
}
func (m *DeviceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceList.Marshal(b, m, deterministic)
}
func (m *DeviceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceList.Merge(m, src)
}
func (m *DeviceList) XXX_Size() int {
	return xxx_messageInfo_DeviceList.Size(m)
}
func (m *DeviceList) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceList.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceList proto.InternalMessageInfo

func (m *DeviceList) GetDevices() []*DeviceInfo {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Version struct {
	Major                uint32   `protobuf:"varint,1,opt,name=Major,proto3" json:"Major,omitempty"`
	Minor                uint32   `protobuf:"varint,2,opt,name=Minor,proto3" json:"Minor,omitempty"`
	Hash                 uint32   `protobuf:"varint,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Version) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Version) GetHash() uint32 {
	if m != nil {
		return m.Hash
	}
	return 0
}

type ServerInfoData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version              *Version `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfoData) Reset()         { *m = ServerInfoData{} }
func (m *ServerInfoData) String() string { return proto.CompactTextString(m) }
func (*ServerInfoData) ProtoMessage()    {}
func (*ServerInfoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *ServerInfoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoData.Unmarshal(m, b)
}
func (m *ServerInfoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoData.Marshal(b, m, deterministic)
}
func (m *ServerInfoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoData.Merge(m, src)
}
func (m *ServerInfoData) XXX_Size() int {
	return xxx_messageInfo_ServerInfoData.Size(m)
}
func (m *ServerInfoData) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoData.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoData proto.InternalMessageInfo

func (m *ServerInfoData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerInfoData) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protocol.DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterEnum("protocol.StatusType", StatusType_name, StatusType_value)
	proto.RegisterType((*Session)(nil), "protocol.Session")
	proto.RegisterType((*DeviceInfo)(nil), "protocol.DeviceInfo")
	proto.RegisterType((*StreamConfig)(nil), "protocol.StreamConfig")
	proto.RegisterType((*ChannelConfig)(nil), "protocol.ChannelConfig")
	proto.RegisterType((*IQData)(nil), "protocol.IQData")
	proto.RegisterType((*DeviceList)(nil), "protocol.DeviceList")
	proto.RegisterType((*Version)(nil), "protocol.Version")
	proto.RegisterType((*ServerInfoData)(nil), "protocol.ServerInfoData")
	proto.RegisterType((*Empty)(nil), "protocol.Empty")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0xc6, 0x89, 0x9b, 0x5c, 0x26, 0x4d, 0xcf, 0x9d, 0x2b, 0x60, 0x55, 0x08, 0x22, 0x0b, 0xa1,
	0x5c, 0xe9, 0x45, 0xa8, 0x9c, 0x38, 0x09, 0xf1, 0xd2, 0x26, 0x57, 0x5a, 0x71, 0xbd, 0xb6, 0xeb,
	0x08, 0xe5, 0x75, 0x49, 0xb6, 0xed, 0x72, 0xf6, 0x3a, 0xac, 0x37, 0x81, 0xf0, 0xcc, 0xaf, 0xe1,
	0x99, 0x9f, 0xc0, 0x1f, 0xe2, 0x1f, 0x20, 0x8f, 0xed, 0xae, 0xdd, 0xb4, 0x4f, 0xc9, 0x7c, 0xf3,
	0xed, 0xec, 0xec, 0x7c, 0x33, 0x63, 0xd8, 0x4e, 0x85, 0x5e, 0x09, 0x3d, 0x5c, 0xe8, 0xc4, 0x24,
	0xf8, 0x8c, 0x7e, 0x66, 0x49, 0x14, 0x7c, 0x01, 0xed, 0x50, 0xa4, 0xa9, 0x4c, 0x14, 0xee, 0xc1,
	0xd6, 0x24, 0xf9, 0x20, 0x94, 0xef, 0xf4, 0x9d, 0x41, 0x87, 0xe5, 0x46, 0xf0, 0x8f, 0x0b, 0x30,
	0x16, 0x2b, 0x39, 0x13, 0xe7, 0xea, 0x26, 0xc1, 0xd7, 0xa5, 0x35, 0x59, 0x2f, 0x04, 0x31, 0x77,
	0x8e, 0xf6, 0x86, 0x65, 0xb8, 0xa1, 0xf5, 0xb1, 0x0a, 0x0f, 0xbf, 0x87, 0xed, 0xd0, 0x68, 0xc1,
	0xe3, 0x51, 0xa2, 0x6e, 0xe4, 0xad, 0xdf, 0xe8, 0x3b, 0x83, 0xee, 0xd1, 0x27, 0xf6, 0x5c, 0xd5,
	0xcb, 0x6a, 0x5c, 0xf4, 0xef, 0x33, 0xf4, 0x9b, 0x94, 0xd8, 0x7d, 0xc2, 0x01, 0x6c, 0xe7, 0x77,
	0x84, 0x42, 0x4b, 0x1e, 0xf9, 0x2e, 0xb9, 0x6b, 0x18, 0x7e, 0x5e, 0xe6, 0xfb, 0x9e, 0xc7, 0xc2,
	0xdf, 0x22, 0x46, 0x05, 0xc1, 0x43, 0xd8, 0xbd, 0xe0, 0x7f, 0xc8, 0x78, 0x19, 0x87, 0x3c, 0x5e,
	0x44, 0x82, 0x71, 0x23, 0xfc, 0x56, 0xdf, 0x19, 0xf4, 0xd8, 0xa6, 0x03, 0xfb, 0xd0, 0x2d, 0xc0,
	0x1f, 0xb9, 0x54, 0x7e, 0x9b, 0x78, 0x55, 0xa8, 0x12, 0x6f, 0x2c, 0x66, 0x32, 0xe6, 0x26, 0xcb,
	0xfb, 0x59, 0x2d, 0x9e, 0x75, 0xe0, 0x01, 0x78, 0x17, 0x52, 0x65, 0xe0, 0xa9, 0x16, 0xbf, 0x2d,
	0x85, 0x9a, 0xad, 0xfd, 0x0e, 0x91, 0x37, 0x70, 0xe2, 0xe6, 0x01, 0x2c, 0x17, 0x0a, 0xee, 0x03,
	0x1c, 0xbf, 0x84, 0xde, 0xf1, 0x78, 0xc4, 0x44, 0x9a, 0x44, 0x4b, 0xca, 0xa0, 0x4b, 0xc4, 0x3a,
	0x58, 0xc9, 0x95, 0x4d, 0x47, 0x77, 0x5c, 0x29, 0x11, 0xa5, 0xfe, 0x76, 0x2d, 0x57, 0xeb, 0xa8,
	0xb0, 0x27, 0x96, 0xdd, 0xab, 0xb1, 0xad, 0x23, 0x98, 0xd7, 0x15, 0xc7, 0x97, 0xd0, 0x64, 0xd3,
	0x11, 0x35, 0x4c, 0xf7, 0xe8, 0x53, 0x2b, 0x7c, 0x71, 0xa0, 0x50, 0x3e, 0xe3, 0x64, 0xd4, 0xc9,
	0x74, 0x54, 0xf4, 0xc8, 0xd3, 0xd4, 0xc9, 0x74, 0x14, 0xfc, 0xe7, 0x40, 0xaf, 0x06, 0xe3, 0x00,
	0x9e, 0x8f, 0x84, 0x32, 0x42, 0xdb, 0x22, 0x39, 0x94, 0xe3, 0x43, 0x38, 0xeb, 0x8c, 0x8a, 0xe4,
	0x0d, 0x22, 0x55, 0x90, 0xcc, 0x7f, 0xb9, 0x12, 0x3a, 0x25, 0x84, 0x5a, 0xaf, 0xc7, 0x2a, 0x08,
	0x7e, 0x05, 0x3b, 0xef, 0x13, 0x1d, 0xf3, 0x48, 0xfe, 0x29, 0xe6, 0xd4, 0x0e, 0x2e, 0x71, 0x1e,
	0xa0, 0xf8, 0x1a, 0x3e, 0x3e, 0x56, 0x3c, 0x4a, 0x6e, 0x4f, 0x65, 0x64, 0x84, 0x3e, 0xe1, 0x6a,
	0xfe, 0xbb, 0x9c, 0x9b, 0x3b, 0x6a, 0xc6, 0x1e, 0x7b, 0xdc, 0x99, 0x75, 0xfd, 0xb1, 0x32, 0x42,
	0x29, 0x4e, 0xdd, 0xd8, 0x61, 0xa5, 0x19, 0xfc, 0xe5, 0x40, 0xeb, 0xfc, 0x7a, 0xcc, 0x0d, 0xc7,
	0xcf, 0xa0, 0x33, 0x91, 0xb1, 0x48, 0x0d, 0x8f, 0x17, 0xf4, 0x4c, 0x97, 0x59, 0x00, 0x0f, 0xa1,
	0x95, 0x1a, 0x6e, 0x96, 0x29, 0x3d, 0xae, 0x36, 0xa6, 0x21, 0xe1, 0x34, 0xa6, 0x05, 0x87, 0xc6,
	0x8c, 0x1e, 0x96, 0xfa, 0x6e, 0xbf, 0x39, 0x68, 0xb0, 0xd2, 0xcc, 0xf6, 0xc2, 0x5b, 0xad, 0x13,
	0x5d, 0x8c, 0x5f, 0x6e, 0x04, 0x3f, 0x94, 0x83, 0xf5, 0x4e, 0xa6, 0x06, 0x87, 0xd0, 0xce, 0xad,
	0xd4, 0x77, 0xfa, 0xcd, 0x41, 0x77, 0x73, 0x27, 0x64, 0xdb, 0x83, 0x95, 0xa4, 0xe0, 0x1c, 0xda,
	0x3f, 0x0b, 0x5d, 0xae, 0x9d, 0x0b, 0xfe, 0x6b, 0xa2, 0x0b, 0x9d, 0x72, 0x83, 0x50, 0xa9, 0x12,
	0x5d, 0x08, 0x93, 0x1b, 0x88, 0xe0, 0x9e, 0xf1, 0xf4, 0xae, 0x50, 0x83, 0xfe, 0x07, 0xd7, 0xb0,
	0x13, 0xd2, 0x6e, 0xcb, 0x6e, 0xa0, 0xb2, 0x20, 0xb8, 0x34, 0xed, 0xf9, 0x1e, 0xa3, 0xff, 0xf8,
	0xf5, 0xfd, 0x85, 0x45, 0x63, 0xed, 0xda, 0x04, 0x0b, 0x07, 0x2b, 0x19, 0x41, 0x1b, 0xb6, 0xde,
	0xc6, 0x0b, 0xb3, 0x3e, 0xf8, 0xdb, 0xa9, 0xae, 0x3b, 0xdc, 0x85, 0x5e, 0xf9, 0x98, 0x15, 0x8f,
	0xe4, 0xdc, 0xfb, 0x08, 0xf7, 0xc0, 0x2b, 0x08, 0x22, 0x35, 0xa1, 0xbc, 0x55, 0x3c, 0xf2, 0x1c,
	0x7c, 0x01, 0xcf, 0x73, 0xf4, 0x58, 0xea, 0x74, 0xb1, 0xbe, 0x54, 0xc2, 0x6b, 0x20, 0xc2, 0x4e,
	0x15, 0x3c, 0xbb, 0xf1, 0x9a, 0xe8, 0x95, 0x2b, 0x8c, 0x99, 0x28, 0x9d, 0x6b, 0xcf, 0xb5, 0x77,
	0xbc, 0x93, 0xb1, 0x08, 0xc7, 0xcc, 0xdb, 0xb2, 0xd1, 0xc2, 0xc5, 0x3a, 0x7f, 0xaa, 0xd7, 0xb2,
	0x27, 0xcf, 0xf8, 0xec, 0x03, 0x3b, 0xf5, 0xda, 0x07, 0x87, 0x00, 0x56, 0x57, 0xec, 0x42, 0xdb,
	0x66, 0xd9, 0x82, 0xc6, 0xe5, 0x4f, 0x9e, 0x83, 0x9d, 0x42, 0x4a, 0xaf, 0x71, 0xf4, 0x6f, 0x03,
	0xba, 0x8c, 0xcf, 0x65, 0x92, 0x47, 0xc4, 0x57, 0xe0, 0x92, 0x92, 0xcf, 0x6d, 0x5d, 0xa8, 0x06,
	0xfb, 0x1b, 0x4a, 0x12, 0xed, 0x0d, 0x74, 0xae, 0x74, 0xb2, 0x92, 0xb9, 0x84, 0x8f, 0x89, 0xbd,
	0xff, 0x28, 0x8a, 0xaf, 0xb2, 0x4e, 0x49, 0x8d, 0x4e, 0xd6, 0x58, 0x91, 0xa0, 0x58, 0xe9, 0xfb,
	0x0f, 0x6f, 0xc7, 0x37, 0x00, 0x56, 0xdd, 0xcd, 0xe4, 0xfc, 0x6a, 0x88, 0x5a, 0x13, 0x7c, 0x07,
	0xee, 0x64, 0xa9, 0x04, 0x3e, 0xf1, 0x91, 0xd9, 0x7f, 0x02, 0xcf, 0xea, 0xc0, 0xa6, 0xe7, 0xd7,
	0x8f, 0x25, 0xe7, 0x59, 0x28, 0x1f, 0xc0, 0x6f, 0x9c, 0x93, 0x97, 0xf0, 0x42, 0x26, 0xc3, 0x5b,
	0xbd, 0x98, 0x0d, 0x75, 0x56, 0xcd, 0xfc, 0x33, 0x7b, 0xe2, 0x55, 0x4a, 0x7b, 0x95, 0x1d, 0xba,
	0x72, 0x7e, 0x69, 0xd1, 0xe9, 0x6f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x32, 0x5e, 0x5f, 0xb0,
	0x8b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RadioServerClient is the client API for RadioServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RadioServerClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error)
	Provision(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*DeviceInfo, error)
	Destroy(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error)
	ServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfoData, error)
	Tune(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (*StreamConfig, error)
	RXIQ(ctx context.Context, in *Session, opts ...grpc.CallOption) (RadioServer_RXIQClient, error)
}

type radioServerClient struct {
	cc *grpc.ClientConn
}

func NewRadioServerClient(cc *grpc.ClientConn) RadioServerClient {
	return &radioServerClient{cc}
}

func (c *radioServerClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error) {
	out := new(DeviceList)
	err := c.cc.Invoke(ctx, "/protocol.RadioServer/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) Provision(ctx context.Context, in *DeviceInfo, opts ...grpc.CallOption) (*DeviceInfo, error) {
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, "/protocol.RadioServer/Provision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) Destroy(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protocol.RadioServer/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) ServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfoData, error) {
	out := new(ServerInfoData)
	err := c.cc.Invoke(ctx, "/protocol.RadioServer/ServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) Tune(ctx context.Context, in *StreamConfig, opts ...grpc.CallOption) (*StreamConfig, error) {
	out := new(StreamConfig)
	err := c.cc.Invoke(ctx, "/protocol.RadioServer/Tune", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *radioServerClient) RXIQ(ctx context.Context, in *Session, opts ...grpc.CallOption) (RadioServer_RXIQClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RadioServer_serviceDesc.Streams[0], "/protocol.RadioServer/RXIQ", opts...)
	if err != nil {
		return nil, err
	}
	x := &radioServerRXIQClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RadioServer_RXIQClient interface {
	Recv() (*IQData, error)
	grpc.ClientStream
}

type radioServerRXIQClient struct {
	grpc.ClientStream
}

func (x *radioServerRXIQClient) Recv() (*IQData, error) {
	m := new(IQData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RadioServerServer is the server API for RadioServer service.
type RadioServerServer interface {
	List(context.Context, *Empty) (*DeviceList, error)
	Provision(context.Context, *DeviceInfo) (*DeviceInfo, error)
	Destroy(context.Context, *Session) (*Empty, error)
	ServerInfo(context.Context, *Empty) (*ServerInfoData, error)
	Tune(context.Context, *StreamConfig) (*StreamConfig, error)
	RXIQ(*Session, RadioServer_RXIQServer) error
}

// UnimplementedRadioServerServer can be embedded to have forward compatible implementations.
type UnimplementedRadioServerServer struct {
}

func (*UnimplementedRadioServerServer) List(ctx context.Context, req *Empty) (*DeviceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedRadioServerServer) Provision(ctx context.Context, req *DeviceInfo) (*DeviceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}
func (*UnimplementedRadioServerServer) Destroy(ctx context.Context, req *Session) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (*UnimplementedRadioServerServer) ServerInfo(ctx context.Context, req *Empty) (*ServerInfoData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerInfo not implemented")
}
func (*UnimplementedRadioServerServer) Tune(ctx context.Context, req *StreamConfig) (*StreamConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tune not implemented")
}
func (*UnimplementedRadioServerServer) RXIQ(req *Session, srv RadioServer_RXIQServer) error {
	return status.Errorf(codes.Unimplemented, "method RXIQ not implemented")
}

func RegisterRadioServerServer(s *grpc.Server, srv RadioServerServer) {
	s.RegisterService(&_RadioServer_serviceDesc, srv)
}

func _RadioServer_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.RadioServer/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.RadioServer/Provision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Provision(ctx, req.(*DeviceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.RadioServer/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Destroy(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).ServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.RadioServer/ServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).ServerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_Tune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadioServerServer).Tune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.RadioServer/Tune",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadioServerServer).Tune(ctx, req.(*StreamConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _RadioServer_RXIQ_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Session)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadioServerServer).RXIQ(m, &radioServerRXIQServer{stream})
}

type RadioServer_RXIQServer interface {
	Send(*IQData) error
	grpc.ServerStream
}

type radioServerRXIQServer struct {
	grpc.ServerStream
}

func (x *radioServerRXIQServer) Send(m *IQData) error {
	return x.ServerStream.SendMsg(m)
}

var _RadioServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.RadioServer",
	HandlerType: (*RadioServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _RadioServer_List_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _RadioServer_Provision_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _RadioServer_Destroy_Handler,
		},
		{
			MethodName: "ServerInfo",
			Handler:    _RadioServer_ServerInfo_Handler,
		},
		{
			MethodName: "Tune",
			Handler:    _RadioServer_Tune_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RXIQ",
			Handler:       _RadioServer_RXIQ_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server.proto",
}
